### ISSUE TITLE
Controller not detected (Cloudy from Github + App Store) on iPhone / iOS 14.4

### ISSUE THREAD

**Issue by bmansvk** [mlostekk/Cloudy#34]
I have MFI (Nimbus+) and Dualshock controller. But Cloudy is unable to detect it and use it (tried also HTML5 Controller test page). 

I tried AppStore version and also compiled Cloudy from source. The same result. But sometimes (after App reinstall) I managed it to detect the controller. But today it stopped to work again.

Both controllers work perfectly using Safari and weblink from the desktop.

**Comment by mlostekk** [comment]
Did you try to disable the „Use custom controller“ flag?

**Comment by bmansvk** [comment]
"Use custom controller" is disabled by default on clean install and gamepad doesn't work when disabled.

But, if I enable it. If seems that gamepad starts to work (it identified as emulated Xbox controller). So it seems issue is solved for me.

BTW: Cloudy from the AppStore works with gamepad without issues on my iPad PRO (and doesn't on iPhone).

Thanks for the support and great app (I did in-app purchase in AppStore version).

**Comment by mlostekk** [comment]
Huge thanks for the support. 

And thats interesting that ipad works, but iphone not. Which versions are those two?

**Comment by bmansvk** [comment]
It stopped to work on iPad yesterday (AppStore version). Self-compiled version, when enabled "custom controller" works (on both iOS and iPadOS).

What is the purpose of this settings? (custom controller).

**Comment by mlostekk** [comment]
This setting is enabling the „native controller to java script bridge“ . some controllers are supported already inside the webview, but if they arent, this setting can be used to natively grab the controller state and inject it into the game stream. but this setting is extracted as its not available in the appstore version because apple rejects it
