### ISSUE TITLE
GeForce Now games never launch.

### ISSUE THREAD

**Issue by Clancey** [mlostekk/Cloudy#4]
![image](https://user-images.githubusercontent.com/256046/99348973-4b892400-2847-11eb-8e2a-ec0ae3583c0b.png)

I only ever see this screen when I start a game. Is there anyway to capture errors? Or view output?

**Comment by Heratiki** [comment]
It's because GFN changed how their page loads each game and it's location. Join the Cloudy Discord and there is a whole chat room dedicated to get them working.

**Comment by mlostekk** [comment]
Should all be working now, closing this, feel free to reopen if it doesnt or join the discord as mentioned
