### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by joedemo42** [mlostekk/Cloudy#6]
Would you kindly consider implementing it? I think this app would be tremendously useful on an tv.

**Comment by mlostekk** [comment]
I would love to do it, but unfortunately WKWebView is not available on tvOS (https://developer.apple.com/documentation/webkit/wkwebview)

**Comment by joedemo42** [comment]
Ah, I see. I wasn’t aware of that. Thanks for pointing it out.
